### ISSUE TITLE
Xacro error (ROS indigo)

### ISSUE THREAD

**Issue by ghost** [bsb808/kingfisher_gazebo#6]
There is an error while running the launch command:

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/xacro/xacro", line 55, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
    eval_self_contained(doc)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 553, in eval_all
    eval_all(body, macros, scoped)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 609, in eval_all
    result = eval_text(at[1], symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 483, in eval_text
    results.append(handle_expr(lex.next()[1][2:-1]))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 470, in handle_expr
    return eval_expr(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 444, in eval_expr
    result = eval_term(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 418, in eval_term
    result = eval_factor(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 398, in eval_factor
    return neg * eval_lit(lex, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 369, in eval_lit
    raise XacroException("Property wasn't defined: %s" % str(ex))
xacro.XacroException: Property wasn't defined: u'min_inertia'
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/lib/xacro/xacro /home/carlos.mendes/kingASV_ws/src/kingfisher_gazebo/urdf/base_gazebo.xacro imu:=true gps:=true microstrain:=true p3d:=true] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro $(arg urdf) imu:=$(arg imu) gps:=$(arg gps) microstrain:=$(arg microstrain) p3d:=$(arg p3d)" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by ghost** [comment]
Just found the indingo folder.
Thanks for the great work.

**Comment by bsb808** [comment]
Sorry for the confusion.  We just recently split into the two branches due to some small changes with xacro between indigo and kinetic.

We are actively working on this - incorporating a simple wave field - so if you have any improvements, we are happy to work on pull requests!

Brian
